const val RELEASE_USER = "hendraanggrian"
const val RELEASE_ARTIFACT = "recyclerview-paginated"
val RELEASE_GROUP = "com.$RELEASE_USER.${RELEASE_ARTIFACT.substringBefore('-')}"
const val RELEASE_VERSION = "0.1"
const val RELEASE_DESC = "Android endless scrolling in its simplest form"
const val RELEASE_WEBSITE = "https://github.com/hendraanggrian/recyclerview-paginated"